### ISSUE TITLE
新版本添加同传名单失败。

### ISSUE THREAD

**Issue by u2shana** [eric2788/bilibili-vup-stream-enhancer#68]
无论添加用户名还是添加uid，都提示的用户不存在。

另外新版会导致这个SC悬浮脚本丢失头像和样式错位，这个脚本有个紧凑模式，遮挡画面比较少。希望能兼容下。
https://greasyfork.org/zh-CN/scripts/484381-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4sc%E8%AE%B0%E5%BD%95%E6%9D%BF

**Comment by eric2788** [comment]
关于SC悬浮脚本那边，如果你有自己的SC悬浮脚本，可以关掉这个功能的

**Comment by eric2788** [comment]
> 无论添加用户名还是添加uid，都提示的用户不存在。
> 
> 另外新版会导致这个SC悬浮脚本丢失头像和样式错位，这个脚本有个紧凑模式，遮挡画面比较少。希望能兼容下。 https://greasyfork.org/zh-CN/scripts/484381-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4sc%E8%AE%B0%E5%BD%95%E6%9D%BF

没想到我的e2e测试没覆盖到添加同传uid那边... orz

**Comment by u2shana** [comment]
> 关于SC悬浮脚本那边，如果你有自己的SC悬浮脚本，可以关掉这个功能的

试过关闭这个功能了，但是还是一样会错位。

**Comment by eric2788** [comment]
@u2shana  另外问个问题，现在有成功把MV2的设定迁移到新版本？

**Comment by u2shana** [comment]
> @u2shana 另外问个问题，现在有成功把MV2的设定迁移到新版本？

成功的，迁移过去设定都保留。

另外还有个同传字幕悬浮框问题，新版的悬浮框无法被拖到播放器画面外侧。不知道有没人和我一样喜欢拉到外面，留下一点点可使面积，优点是不怎么挡画面，缺点是一不小心可能全部拉出去得刷新网页重置才行。

**Comment by eric2788** [comment]
> > @u2shana 另外问个问题，现在有成功把MV2的设定迁移到新版本？
> 
> 成功的，迁移过去设定都保留。
> 
> 另外还有个同传字幕悬浮框问题，新版的悬浮框无法被拖到播放器画面外侧。不知道有没人和我一样喜欢拉到外面，留下一点点可使面积，优点是不怎么挡画面，缺点是一不小心可能全部拉出去得刷新网页重置才行。

新版本加了切换显示隐藏的按钮，在关闭特效旁边

**Comment by u2shana** [comment]
> > > @u2shana 另外问个问题，现在有成功把MV2的设定迁移到新版本？
> > 
> > 
> > 成功的，迁移过去设定都保留。
> > 另外还有个同传字幕悬浮框问题，新版的悬浮框无法被拖到播放器画面外侧。不知道有没人和我一样喜欢拉到外面，留下一点点可使面积，优点是不怎么挡画面，缺点是一不小心可能全部拉出去得刷新网页重置才行。
> 
> 新版本加了切换显示隐藏的按钮，在关闭特效旁边

关闭后就看不了同传了。场景是这样的，一般来说网页全屏下，左右两边都会有黑边，为了节省空间，我习惯把悬浮窗放这个位置

**Comment by eric2788** [comment]
@u2shana 在吗？去 artifacts 那边下载测试版本 https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8233719478 看看这个问题修了没
