### ISSUE TITLE
MV3新版本同传字幕悬浮框无法拉出到播放器画面外

### ISSUE THREAD

**Issue by u2shana** [eric2788/bilibili-vup-stream-enhancer#69]
同传字幕悬浮框问题，新版的悬浮框无法被拖到播放器画面外侧。不知道有没人和我一样喜欢拉到外面，留下一点点可使面积，优点是不怎么挡画面，缺点是一不小心可能全部拉出去得刷新网页重置才行。

https://github.com/eric2788/bilibili-vup-stream-enhancer/issues/68#issuecomment-1987800988

**Comment by eric2788** [comment]
等跑完出 artifacts 之後，你去試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8251943152

**Comment by u2shana** [comment]
> @u2shana 等跑完出 artifacts 之後，你去試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8251943152

这个改动有了

**Comment by eric2788** [comment]
> > @u2shana 等跑完出 artifacts 之後，你去試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8251943152
> 
> 这个改动有了

我在想要不要搞设定开关锁定移动范围播放器画面 🤔 但想不到锁定的好处是啥
