### ISSUE TITLE
新版本 CSS 覆盖了其他网页/脚本的样式

### ISSUE THREAD

**Issue by u2shana** [eric2788/bilibili-vup-stream-enhancer#70]
新版会导致这个SC悬浮脚本丢失头像和样式错位，这个脚本有个紧凑模式，遮挡画面比较少。试过关闭本扩展的SC功能了，但是还是一样会错位。
https://greasyfork.org/zh-CN/scripts/484381-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4sc%E8%AE%B0%E5%BD%95%E6%9D%BF

此外，如下图整个页面的字体样式也会收到影响
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/ee816eb9-b7d0-4353-9168-ab1b98ecf2b5)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/53eb2025-15e4-4acf-8a00-40b334c152ef)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/ad10a4cb-66c7-46cb-a57b-ae7b64f174f6)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/55b737a1-69aa-463e-a12e-94b200e8c831)

下面的图都是开启同传功能的状态，很明显看到字体变了

**Comment by eric2788** [comment]
新版本本扩展的css使用了shadow-root，照计是不会影响到其他css的，有空我再看看

**Comment by eric2788** [comment]
有截图看看是怎么不兼容吗

**Comment by u2shana** [comment]
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/5c257f0b-1da6-4a77-9366-dab54d6ba071)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/b88436f9-ea2e-49d7-a274-24d76808a6b3)
正常是这样的
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/0fb39f05-95b4-40ab-9051-e7c23d62fd79)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/234ff09e-8762-4cb8-8183-d16e11435b01)

**Comment by eric2788** [comment]
確定禁用本擴展後恢復正常？

**Comment by u2shana** [comment]
> 確定禁用本擴展後恢復正常？

对的，上面的2张正常的图就是禁用之后截图的

**Comment by eric2788** [comment]
@u2shana https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8246108937?pr=73 试试这个测试版本

**Comment by u2shana** [comment]
> @u2shana https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8246916287 试试这个测试版本

测试了下，上面说的问题都解决了

**Comment by u2shana** [comment]
又发现一个兼容性问题。https://chrome.google.com/webstore/detail/kpbnombpnpcffllnianjibmpadjolanh
这个ACG助手（前身bilibili助手）有一个版聊模式的功能，就是下图的样子
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/4ddf23a6-b7dc-4e68-9974-d3c4e9fefcd4)
但是配合本扩展后，如果退出网页全屏再重新开启，版聊模式就会消失。但是如果鼠标按住同传悬浮框，版聊模式则会显现出来

**Comment by eric2788** [comment]
> 又发现一个兼容性问题。https://chrome.google.com/webstore/detail/kpbnombpnpcffllnianjibmpadjolanh 这个ACG助手（前身bilibili助手）有一个版聊模式的功能，就是下图的样子 ![image](https://private-user-images.githubusercontent.com/14146754/312069810-4ddf23a6-b7dc-4e68-9974-d3c4e9fefcd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDk4OTQsIm5iZiI6MTcxMDI0OTU5NCwicGF0aCI6Ii8xNDE0Njc1NC8zMTIwNjk4MTAtNGRkZjIzYTYtYjdkYy00ZTY4LTk5NzQtZDNjNGU5ZmVmY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEzMTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxODk0NWExNDQ4YTcwMDY4MDQ1NWNiNTM0Y2JiMTQwMjVlMjYyNzAxMzM2YTBiZWZmMzNjYTM0YjYwZjQxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9IUsB5Aw5OJA9ZN1dLI5vbb4nrFWBazdU9dTw1LmDpg) 但是配合本扩展后，如果退出网页全屏再重新开启，版聊模式就会消失。但是如果鼠标按住同传悬浮框，版聊模式则会显现出来

在測試版本下？

**Comment by eric2788** [comment]
你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217

**Comment by u2shana** [comment]
> 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217

不行，一样有消失的问题

**Comment by eric2788** [comment]
> > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> 
> 不行，一样有消失的问题

你這個擴展我找不到源碼，我要禮拜六日才有空在家研究

**Comment by u2shana** [comment]
> > > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> > 
> > 
> > 不行，一样有消失的问题
> 
> 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究

刚才测试了下，发现无法复原问题了，很怪。
不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小

**Comment by eric2788** [comment]
> > > > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> > > 
> > > 
> > > 不行，一样有消失的问题
> > 
> > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> 
> 刚才测试了下，发现无法复原问题了，很怪。
> 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小

這個不是bug，是故意不再這麼搞的

**Comment by eric2788** [comment]
> > > > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> > > 
> > > 
> > > 不行，一样有消失的问题
> > 
> > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> 
> 刚才测试了下，发现无法复原问题了，很怪。
> 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小

那再有問題再說 🤔 我記得我是沒有改過全屏的元素

**Comment by u2shana** [comment]
> > > > > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> > > > 
> > > > 
> > > > 不行，一样有消失的问题
> > > 
> > > 
> > > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> > 
> > 
> > 刚才测试了下，发现无法复原问题了，很怪。
> > 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小
> 
> 那再有問題再說 🤔 我記得我是沒有改過全屏的元素

今天试了下谷歌商店的新版本，我两台电脑都复现了这个问题😂

**Comment by eric2788** [comment]
> > > > > > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> > > > > 
> > > > > 
> > > > > 不行，一样有消失的问题
> > > > 
> > > > 
> > > > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> > > 
> > > 
> > > 刚才测试了下，发现无法复原问题了，很怪。
> > > 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小
> > 
> > 
> > 那再有問題再說 🤔 我記得我是沒有改過全屏的元素
> 
> 今天试了下谷歌商店的新版本，我两台电脑都复现了这个问题😂

你可以開新issue，但修復后不一定短時間内進行正式版本更新，届時你可能需要暫時安裝未封裝擴展來解決這個問題 🤔

**Comment by eric2788** [comment]
> > > > > > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> > > > > 
> > > > > 
> > > > > 不行，一样有消失的问题
> > > > 
> > > > 
> > > > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> > > 
> > > 
> > > 刚才测试了下，发现无法复原问题了，很怪。
> > > 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小
> > 
> > 那再有問題再說 🤔 我記得我是沒有改過全屏的元素
> 
> 今天试了下谷歌商店的新版本，我两台电脑都复现了这个问题😂

新版本已更新，就是不知道有沒有修復到這個

**Comment by u2shana** [comment]
> > > > > > > 你試試這個版本: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217
> > > > > > 
> > > > > > 
> > > > > > 不行，一样有消失的问题
> > > > > 
> > > > > 
> > > > > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> > > > 
> > > > 
> > > > 刚才测试了下，发现无法复原问题了，很怪。
> > > > 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小
> > > 
> > > 
> > > 那再有問題再說 🤔 我記得我是沒有改過全屏的元素
> > 
> > 
> > 今天试了下谷歌商店的新版本，我两台电脑都复现了这个问题😂
> 
> 新版本已更新，就是不知道有沒有修復到這個

是指“退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小”这个吗，试了一下没问题了

**Comment by eric2788** [comment]
> > > > > > > > 你試試這個版本: [eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217)
> > > > > > > 
> > > > > > > 
> > > > > > > 不行，一样有消失的问题
> > > > > > 
> > > > > > 
> > > > > > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> > > > > 
> > > > > 
> > > > > 刚才测试了下，发现无法复原问题了，很怪。
> > > > > 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小
> > > > 
> > > > 
> > > > 那再有問題再說 🤔 我記得我是沒有改過全屏的元素
> > > 
> > > 
> > > 今天试了下谷歌商店的新版本，我两台电脑都复现了这个问题😂
> > 
> > 
> > 新版本已更新，就是不知道有沒有修復到這個
> 
> 是指“退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小”这个吗，试了一下没问题了

不是，我是指這個問題: https://github.com/eric2788/bilibili-vup-stream-enhancer/issues/70#issuecomment-1991512956

**Comment by u2shana** [comment]
> > > > > > > > > 你試試這個版本: [eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/8249712217)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不行，一样有消失的问题
> > > > > > > 
> > > > > > > 
> > > > > > > 你這個擴展我找不到源碼，我要禮拜六日才有空在家研究
> > > > > > 
> > > > > > 
> > > > > > 刚才测试了下，发现无法复原问题了，很怪。
> > > > > > 不过也发现了个问题，退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小
> > > > > 
> > > > > 
> > > > > 那再有問題再說 🤔 我記得我是沒有改過全屏的元素
> > > > 
> > > > 
> > > > 今天试了下谷歌商店的新版本，我两台电脑都复现了这个问题😂
> > > 
> > > 
> > > 新版本已更新，就是不知道有沒有修復到這個
> > 
> > 
> > 是指“退出网页全屏再重进网页全屏，同传悬浮框会复原默认位置和大小”这个吗，试了一下没问题了
> 
> 不是，我是指這個問題: [#70 (comment)](https://github.com/eric2788/bilibili-vup-stream-enhancer/issues/70#issuecomment-1991512956)

这个问题2.0.1版本也没复现过了
