### ISSUE TITLE
勾选启动同传后，页面所有字体都会改变

### ISSUE THREAD

**Issue by u2shana** [eric2788/bilibili-vup-stream-enhancer#71]
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/ee816eb9-b7d0-4353-9168-ab1b98ecf2b5)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/53eb2025-15e4-4acf-8a00-40b334c152ef)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/ad10a4cb-66c7-46cb-a57b-ae7b64f174f6)
![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/55b737a1-69aa-463e-a12e-94b200e8c831)

下面的图都是开启同传功能的状态，很明显看到字体变了

**Comment by eric2788** [comment]
這也太奇怪了，你的瀏覽器支援 shadow root 嗎？瀏覽器和版本我看看？

**Comment by u2shana** [comment]
> shadow root

![image](https://github.com/eric2788/bilibili-vup-stream-enhancer/assets/14146754/1056dc80-b2d5-4b3e-8a6b-18bab3786393)
最新的stable

**Comment by eric2788** [comment]
> 另外你這個問題基本上和 #70 是一樣的，基本上都是 shadow root 不支援的問題，你可以把他們合併，

你和 #70 合併一下issue
