### ISSUE TITLE
在不开播的直播间里不显示面板按钮和

### ISSUE THREAD

**Issue by u2shana** [eric2788/bilibili-vup-stream-enhancer#83]
### 感谢您抽出时间填写此问题回报！

- [X] 我已经搜索了现有的问题，并且确认我的问题是独特的

### 问题描述

在不开播的直播间里不显示面板按钮，但是看控制台是有运行的信息的。

### 期望结果

希望不开播也能显示面板按钮

### 复现步骤

1

### 浏览器

chrome最新

### 扩展版本

最新

**Comment by eric2788** [comment]
你這個應該是功能請求吧，不過爲啥要顯示

**Comment by u2shana** [comment]
> 你這個應該是功能請求吧，不過爲啥要顯示

确实搞错了。要显示是因为如果不关网页蹲开播的话，开播后不会加载插件功能，需要刷新一下网页，但是刷新可能会造成丢失原生推流，转而获取二压直播推流

**Comment by eric2788** [comment]
> > 你這個應該是功能請求吧，不過爲啥要顯示
> 
> 确实搞错了。要显示是因为如果不关网页蹲开播的话，开播后不会加载插件功能，需要刷新一下网页，但是刷新可能会造成丢失原生推流，转而获取二压直播推流

我尋思未開播之前加載插件功能應該也會有問題吧 🤔

**Comment by eric2788** [comment]
但是 `会造成丢失原生推流，转而获取二压直播推流` 這個我是聞所未聞 🤔 那不就是開播之後的所有人進來都是二壓麽

**Comment by u2shana** [comment]
> 但是 `会造成丢失原生推流，转而获取二压直播推流` 這個我是聞所未聞 🤔 那不就是開播之後的所有人進來都是二壓麽

是这样的，开播后的几十秒内推的是原生流，之后就通过B站二压的“原画”流了。实际上我关注的一个主播推的2K流，但是如果晚进去直播间后，就变成1080p码率很低的的二压流了

这个脚本的0.5.3版本介绍有提及到
https://greasyfork.org/zh-CN/scripts/453967-bilibili%E7%9B%B4%E6%92%AD%E8%87%AA%E5%8A%A8%E8%BF%BD%E5%B8%A7

**Comment by eric2788** [comment]
我要先想想，先不説錄製功能肯定無法在開播前使用，還有直播開始時間戳在開播前也無法取得，會影響同傳彈幕/SC記錄的時間戳

**Comment by eric2788** [comment]
我嘗試在開發人員選項那邊加一個 force boost (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果

**Comment by u2shana** [comment]
> 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果

我尝试下载了action版本[301a692](https://github.com/eric2788/bilibili-vup-stream-enhancer/commit/301a692bdb2a0c664455e5434437e7126bc9770a)，但是在开发者选项找不到这个选项

**Comment by eric2788** [comment]
> > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> 
> 我尝试下载了action版本[301a692](https://github.com/eric2788/bilibili-vup-stream-enhancer/commit/301a692bdb2a0c664455e5434437e7126bc9770a)，但是在开发者选项找不到这个选项

用 [feature/forceboot](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11343916942) 分支

**Comment by u2shana** [comment]
> > > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> > 
> > 
> > 我尝试下载了action版本[301a692](https://github.com/eric2788/bilibili-vup-stream-enhancer/commit/301a692bdb2a0c664455e5434437e7126bc9770a)，但是在开发者选项找不到这个选项
> 
> 用 [feature/forceboot](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11343916942) 分支

这个分支没有artifacts啊

**Comment by eric2788** [comment]
> > > > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> > > 
> > > 
> > > 我尝试下载了action版本[301a692](https://github.com/eric2788/bilibili-vup-stream-enhancer/commit/301a692bdb2a0c664455e5434437e7126bc9770a)，但是在开发者选项找不到这个选项
> > 
> > 
> > 用 [feature/forceboot](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11343916942) 分支
> 
> 这个分支没有artifacts啊

剛加，試試這個： https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11346554787

**Comment by eric2788** [comment]
> > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> 
> 测试了一下，好像没有效果。挂着窗口直播上线后，重启插件，虽然有挂接成功的提示，但是并没有加载悬浮窗（但是如果上次下播后没有刷新页面，下次开播能保留悬浮窗，并且正常工作）。另外上个月播放器改版，嵌入播放器的悬浮窗开关按钮消失了

悬浮窗是指功能菜單？你給我一下下播時的截圖和開播後按下重啟的截圖

**Comment by u2shana** [comment]
> > > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> > 
> > 
> > 测试了一下，好像没有效果。挂着窗口直播上线后，重启插件，虽然有挂接成功的提示，但是并没有加载悬浮窗（但是如果上次下播后没有刷新页面，下次开播能保留悬浮窗，并且正常工作）。另外上个月播放器改版，嵌入播放器的悬浮窗开关按钮消失了
> 
> 悬浮窗是指功能菜單？你給我一下下播時的截圖和開播後按下重啟的截圖

就是这个字幕板还有全屏时的悬浮字幕板，正常情况下，如果未开播时进去是没有这个板的，但是如果下播后一直不刷新就能留着，并且下次开播后能正常工作。至于重启这功能，我测下来好像并不需要特意去按重启
![image](https://github.com/user-attachments/assets/5e0d7a32-6e1f-4a62-b3ea-ee24a6dc7d8d)

**Comment by eric2788** [comment]
> > > > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> > > 
> > > 
> > > 测试了一下，好像没有效果。挂着窗口直播上线后，重启插件，虽然有挂接成功的提示，但是并没有加载悬浮窗（但是如果上次下播后没有刷新页面，下次开播能保留悬浮窗，并且正常工作）。另外上个月播放器改版，嵌入播放器的悬浮窗开关按钮消失了
> > 
> > 
> > 悬浮窗是指功能菜單？你給我一下下播時的截圖和開播後按下重啟的截圖
> 
> 就是这个字幕板还有全屏时的悬浮字幕板，正常情况下，如果未开播时进去是没有这个板的，但是如果下播后一直不刷新就能留着，并且下次开播后能正常工作。至于重启这功能，我测下来好像并不需要特意去按重启 ![image](https://private-user-images.githubusercontent.com/14146754/376647900-5e0d7a32-6e1f-4a62-b3ea-ee24a6dc7d8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDE3NjUsIm5iZiI6MTcyOTAwMTQ2NSwicGF0aCI6Ii8xNDE0Njc1NC8zNzY2NDc5MDAtNWUwZDdhMzItNmUxZi00YTYyLWIzZWEtZWUyNGE2ZGM3ZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0MTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYWNjNDg4N2Y2YzQ4MjExNTMxZjg5MGM5NjQ4MDJiOTE2NmI2ZGQxNmJjNTE5ZjY4YjM4NmFjNTZiMjY3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bRGw9_VmjJZbNbGQrsFpD9T4BL6QwqEoQJyxMHHERBs)

不對吧，以我目前的設計是：

- 未開播前，只有功能菜單
- 開播後，功能菜單還在，但是其他功能依然不存在
- 開播後按下重啟按鈕，功能菜單和所有功能都一併開啟

**Comment by u2shana** [comment]
> > > > > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> > > > 
> > > > 
> > > > 测试了一下，好像没有效果。挂着窗口直播上线后，重启插件，虽然有挂接成功的提示，但是并没有加载悬浮窗（但是如果上次下播后没有刷新页面，下次开播能保留悬浮窗，并且正常工作）。另外上个月播放器改版，嵌入播放器的悬浮窗开关按钮消失了
> > > 
> > > 
> > > 悬浮窗是指功能菜單？你給我一下下播時的截圖和開播後按下重啟的截圖
> > 
> > 
> > 就是这个字幕板还有全屏时的悬浮字幕板，正常情况下，如果未开播时进去是没有这个板的，但是如果下播后一直不刷新就能留着，并且下次开播后能正常工作。至于重启这功能，我测下来好像并不需要特意去按重启 ![image](https://private-user-images.githubusercontent.com/14146754/376647900-5e0d7a32-6e1f-4a62-b3ea-ee24a6dc7d8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDE3NjUsIm5iZiI6MTcyOTAwMTQ2NSwicGF0aCI6Ii8xNDE0Njc1NC8zNzY2NDc5MDAtNWUwZDdhMzItNmUxZi00YTYyLWIzZWEtZWUyNGE2ZGM3ZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0MTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYWNjNDg4N2Y2YzQ4MjExNTMxZjg5MGM5NjQ4MDJiOTE2NmI2ZGQxNmJjNTE5ZjY4YjM4NmFjNTZiMjY3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bRGw9_VmjJZbNbGQrsFpD9T4BL6QwqEoQJyxMHHERBs)
> 
> 不對吧，以我目前的設計是：
> 
> * 未開播前，只有功能菜單
> * 開播後，功能菜單還在，但是其他功能依然不存在
> * 開播後按下重啟按鈕，功能菜單和所有功能都一併開啟
> 
> 你說說看你現在的情況

* 未開播前，只有功能菜單🗸
* 開播後，功能菜單還在，但是其他功能依然不存在🗸
* 開播後按下重啟按鈕，功能菜單和所有功能都一併開啟🗴 这一步其他功能跟随启动
*

**Comment by eric2788** [comment]
> > > > > > 我嘗試在開發人員選項那邊加一個 force boot (强制啓動), 你配合 重新啓動 按鈕, 看看能否達成你要的效果
> > > > > 
> > > > > 
> > > > > 测试了一下，好像没有效果。挂着窗口直播上线后，重启插件，虽然有挂接成功的提示，但是并没有加载悬浮窗（但是如果上次下播后没有刷新页面，下次开播能保留悬浮窗，并且正常工作）。另外上个月播放器改版，嵌入播放器的悬浮窗开关按钮消失了
> > > > 
> > > > 
> > > > 悬浮窗是指功能菜單？你給我一下下播時的截圖和開播後按下重啟的截圖
> > > 
> > > 
> > > 就是这个字幕板还有全屏时的悬浮字幕板，正常情况下，如果未开播时进去是没有这个板的，但是如果下播后一直不刷新就能留着，并且下次开播后能正常工作。至于重启这功能，我测下来好像并不需要特意去按重启 ![image](https://private-user-images.githubusercontent.com/14146754/376647900-5e0d7a32-6e1f-4a62-b3ea-ee24a6dc7d8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDE3NjUsIm5iZiI6MTcyOTAwMTQ2NSwicGF0aCI6Ii8xNDE0Njc1NC8zNzY2NDc5MDAtNWUwZDdhMzItNmUxZi00YTYyLWIzZWEtZWUyNGE2ZGM3ZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE0MTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYWNjNDg4N2Y2YzQ4MjExNTMxZjg5MGM5NjQ4MDJiOTE2NmI2ZGQxNmJjNTE5ZjY4YjM4NmFjNTZiMjY3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bRGw9_VmjJZbNbGQrsFpD9T4BL6QwqEoQJyxMHHERBs)
> > 
> > 
> > 不對吧，以我目前的設計是：
> > 
> > * 未開播前，只有功能菜單
> > * 開播後，功能菜單還在，但是其他功能依然不存在
> > * 開播後按下重啟按鈕，功能菜單和所有功能都一併開啟
> > 
> > 你說說看你現在的情況
> 
> * 未開播前，只有功能菜單🗸
> * 開播後，功能菜單還在，但是其他功能依然不存在🗸
> * 開播後按下重啟按鈕，功能菜單和所有功能都一併開啟🗴 这一步其他功能并没有跟随启动

哦，那我懂了

**Comment by eric2788** [comment]
試試: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11348456326

**Comment by u2shana** [comment]
> 試試: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11348456326

这个版本重启后功能可以正常呼出了

**Comment by eric2788** [comment]
> > 試試: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11348456326
> 
> 这个版本重启后功能可以正常呼出了

但是這個版本是大改了生命週期，我還是盡量不想破壞原有的週期架構，還是要再想一下

**Comment by eric2788** [comment]
@u2shana 我更新了另一個版本，這次直接離線時功能全開，但是快速切片那些功能由於沒有直播流所以依然還是需要重新啟動。

**Comment by eric2788** [comment]
> @u2shana 我更新了另一個版本，這次直接離線時功能全開，但是快速切片那些功能由於沒有直播流所以依然還是需要重新啟動。
> 
> https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11366622803

@u2shana 这个版本没有问题我就合并咯

**Comment by u2shana** [comment]
> > @u2shana 我更新了另一個版本，這次直接離線時功能全開，但是快速切片那些功能由於沒有直播流所以依然還是需要重新啟動。
> > https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11366622803
> 
> @u2shana 这个版本没有问题我就合并咯

用了几天，新特性都正常，但是有个问题像是从旧版就一直存在：快速切片的2个按钮经常不显示，但是这时使用快捷键，截图和录像功能都生效的

**Comment by eric2788** [comment]
> > > @u2shana 我更新了另一個版本，這次直接離線時功能全開，但是快速切片那些功能由於沒有直播流所以依然還是需要重新啟動。
> > > https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11366622803
> > 
> > 
> > @u2shana 这个版本没有问题我就合并咯
> 
> 用了几天，新特性都正常，但是有个问题像是从旧版就一直存在：快速切片的2个按钮经常不显示，但是这时使用快捷键，截图和录像功能都生效的

这个你开新issue吧，另外不显示的时候能否提供一下
- 截图
- 对着本应该出现的位置按下右键 -> 查看元素, 然后截图给我看看他的 HTML 区域
