### ISSUE TITLE
[Bug]: 快速切片按钮不加载

### ISSUE THREAD

**Issue by u2shana** [eric2788/bilibili-vup-stream-enhancer#86]
### 感谢您抽出时间填写此问题回报！

- [X] 我已经搜索了现有的问题，并且确认我的问题是独特的

### 问题描述

![image](https://github.com/user-attachments/assets/f7c991fb-a07f-43d6-9fcd-840bb74b55e1)
![image](https://github.com/user-attachments/assets/4fbdf039-391b-4f63-a55c-3c080d41e499)

偶尔会出现按钮不加载的情况，但是此时使用快捷键，对应功能生效的。
出现频率不算高，但如果同时使用其他带有嵌入到这个位置按钮的脚本（比如https://greasyfork.org/zh-CN/scripts/406048-bilibili-live-tasks-helper），触发概率会大大升高
所以猜测代码加载时机或者别的原因出了问题

### 期望结果

1

### 复现步骤

1

### 浏览器

chrome130

### 扩展版本

2.0.2

**Comment by eric2788** [comment]
也就是説跟其他脚本有衝突？
你有確保過再完全沒有其他脚本的情況下依然出現這種狀況嗎 🤔

**Comment by u2shana** [comment]
> 也就是説跟其他脚本有衝突？ 你有確保過再完全沒有其他脚本的情況下依然出現這種狀況嗎 🤔

尝试过关闭其他脚本，还是会有这种情况出现，但是出现概率变得低很多

**Comment by eric2788** [comment]
![image](https://github.com/user-attachments/assets/f973e9ad-28c7-4b42-8134-1c99a991dccf)
![image](https://github.com/user-attachments/assets/13eee36c-6ebe-4fe1-bedb-37be24955788)

就這麽看上去確實是由衝突

**Comment by eric2788** [comment]
> > 也就是説跟其他脚本有衝突？ 你有確保過再完全沒有其他脚本的情況下依然出現這種狀況嗎 🤔
> 
> 尝试过关闭其他脚本，还是会有这种情况出现，但是出现概率变得低很多

設定確定設置了顯示對吧，那 F12 打開 console 有出現錯誤嗎？

**Comment by u2shana** [comment]
> > > 也就是説跟其他脚本有衝突？ 你有確保過再完全沒有其他脚本的情況下依然出現這種狀況嗎 🤔
> > 
> > 
> > 尝试过关闭其他脚本，还是会有这种情况出现，但是出现概率变得低很多
> 
> 設定確定設置了顯示對吧，那 F12 打開 console 有出現錯誤嗎？

![image](https://github.com/user-attachments/assets/ddb43685-fb8c-4f3a-9c78-afc4c0a61958)

**Comment by eric2788** [comment]
> > > > 也就是説跟其他脚本有衝突？ 你有確保過再完全沒有其他脚本的情況下依然出現這種狀況嗎 🤔
> > > 
> > > 
> > > 尝试过关闭其他脚本，还是会有这种情况出现，但是出现概率变得低很多
> > 
> > 
> > 設定確定設置了顯示對吧，那 F12 打開 console 有出現錯誤嗎？
> 
> ![image](https://private-user-images.githubusercontent.com/14146754/378686695-ddb43685-fb8c-4f3a-9c78-afc4c0a61958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzM1MDYsIm5iZiI6MTcyOTU3MzIwNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg2ODY2OTUtZGRiNDM2ODUtZmI4Yy00ZjNhLTljNzgtYWZjNGMwYTYxOTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMGQ1YzRhYzhjMmY2OWM3YjJmZDVlMjhlMzk4YjMwMzFjZjM0ZGU1NTgwYThhY2RhYTlmYWQxZWEwOTI5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Sci_PwyfSc5fCCTD9Zo32gZqyfhUDibK0mLsDe1bbU)

第一個錯誤是怎麽來的，這個錯誤應該會導致插件完全無法運作
另外第三個 warning 應該是字幕懸浮區塊切換按鈕失效？

**Comment by u2shana** [comment]
> > > > > 也就是説跟其他脚本有衝突？ 你有確保過再完全沒有其他脚本的情況下依然出現這種狀況嗎 🤔
> > > > 
> > > > 
> > > > 尝试过关闭其他脚本，还是会有这种情况出现，但是出现概率变得低很多
> > > 
> > > 
> > > 設定確定設置了顯示對吧，那 F12 打開 console 有出現錯誤嗎？
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/14146754/378686695-ddb43685-fb8c-4f3a-9c78-afc4c0a61958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzM1MDYsIm5iZiI6MTcyOTU3MzIwNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg2ODY2OTUtZGRiNDM2ODUtZmI4Yy00ZjNhLTljNzgtYWZjNGMwYTYxOTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMGQ1YzRhYzhjMmY2OWM3YjJmZDVlMjhlMzk4YjMwMzFjZjM0ZGU1NTgwYThhY2RhYTlmYWQxZWEwOTI5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Sci_PwyfSc5fCCTD9Zo32gZqyfhUDibK0mLsDe1bbU)
> 
> 第一個錯誤是怎麽發生的，這個錯誤應該會導致插件完全無法運作 另外第三個 warning 應該是字幕懸浮區塊切換按鈕失效？

我搞错了，第一个错误产生的原因是商店版本的插件忘记关了。第二个waring就是快速切片按钮没加载出来时的警告，第三个warning如上一个issue所说，自从B站上个月样式改版后那个按钮就失效了

**Comment by eric2788** [comment]
> > > > > > 也就是説跟其他脚本有衝突？ 你有確保過再完全沒有其他脚本的情況下依然出現這種狀況嗎 🤔
> > > > > 
> > > > > 
> > > > > 尝试过关闭其他脚本，还是会有这种情况出现，但是出现概率变得低很多
> > > > 
> > > > 
> > > > 設定確定設置了顯示對吧，那 F12 打開 console 有出現錯誤嗎？
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/14146754/378686695-ddb43685-fb8c-4f3a-9c78-afc4c0a61958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzM1MDYsIm5iZiI6MTcyOTU3MzIwNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg2ODY2OTUtZGRiNDM2ODUtZmI4Yy00ZjNhLTljNzgtYWZjNGMwYTYxOTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMGQ1YzRhYzhjMmY2OWM3YjJmZDVlMjhlMzk4YjMwMzFjZjM0ZGU1NTgwYThhY2RhYTlmYWQxZWEwOTI5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Sci_PwyfSc5fCCTD9Zo32gZqyfhUDibK0mLsDe1bbU)
> > 
> > 
> > 第一個錯誤是怎麽發生的，這個錯誤應該會導致插件完全無法運作 另外第三個 warning 應該是字幕懸浮區塊切換按鈕失效？
> 
> 我搞错了，第一个错误产生的原因是商店版本的插件忘记关了。第二个waring就是快速切片按钮没加载出来时的警告，第三个warning如上一个issue所说，自从B站上个月样式改版后那个按钮就失效了

不對，第二個 warning 也是 同傳字幕 功能的，跟 快速切片 無關

**Comment by eric2788** [comment]
你試試去直播間打開 F12 `元素`, 輸入 `document.querySelector('div.upper-row > div.left-ctnr.left-header-area')` 看看有沒有html，還是出 null

**Comment by u2shana** [comment]
![image](https://github.com/user-attachments/assets/510942c3-7db3-4a45-9b90-7df3b0cc3d98)
这是关了其他脚本有按钮的情况
![image](https://github.com/user-attachments/assets/51e13d87-c2dd-48c8-908e-dfdfb7e24d59)
这是开了别的脚本但是还有按钮的情况
![image](https://github.com/user-attachments/assets/eda7e985-beb9-4d54-9eda-1757d0fbaf30)
这是开了别的脚本但是没有显示按钮的情况

**Comment by eric2788** [comment]
> ![image](https://private-user-images.githubusercontent.com/14146754/378716891-510942c3-7db3-4a45-9b90-7df3b0cc3d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODExMzYsIm5iZiI6MTcyOTU4MDgzNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg3MTY4OTEtNTEwOTQyYzMtN2RiMy00YTQ1LTliOTAtN2RmM2IwY2MzZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMGI3ZDExMjY2ODNiNDZiZWU2NDY2ZGQ3MDlmYzBiZTNjNzY3YzZmNWJkNzYyNWU4YjlkMTBmNzY3MjJhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BVkyU94p7yM6GuJf5utAlLER7JjM31JhGCLWK9OA4sA) 这是关了其他脚本有按钮的情况 ![image](https://private-user-images.githubusercontent.com/14146754/378717650-51e13d87-c2dd-48c8-908e-dfdfb7e24d59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODExMzYsIm5iZiI6MTcyOTU4MDgzNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg3MTc2NTAtNTFlMTNkODctYzJkZC00OGM4LTkwOGUtZGZkZmI3ZTI0ZDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZTRjZDVmNGZkNDE0N2JmZTg1MzY2MzA5MmFlM2E3MjcyOTEzMDEyNmQyN2I0MjM0YjBhZmQzZmYzNTRlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E9zefctR4LXxg7HOIVUuUaPlCVMGoXw1iM4r-Q3Hvck) 这是开了别的脚本但是还有按钮的情况 ![image](https://private-user-images.githubusercontent.com/14146754/378718320-eda7e985-beb9-4d54-9eda-1757d0fbaf30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODExMzYsIm5iZiI6MTcyOTU4MDgzNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg3MTgzMjAtZWRhN2U5ODUtYmViOS00ZDU0LTllZGEtMTc1N2QwZmJhZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNTdlNmM4MzhiZTkwZDQzYTNiYWJmZjAxNzI3MzY4MGJjYThjMTRmNmM2ZjliM2QyYmE1NTY2NjFiYWM1NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c6fY7DwTBRInipihBXkhJIFdCnyi7xzn4_tivPFMlxY) 这是开了别的脚本但是没有显示按钮的情况

第三圖，這是明顯是跟其他脚本衝突了
有沒有沒開其他脚本但是沒有顯示按鈕的截圖？

**Comment by u2shana** [comment]
> > ![image](https://private-user-images.githubusercontent.com/14146754/378716891-510942c3-7db3-4a45-9b90-7df3b0cc3d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODExMzYsIm5iZiI6MTcyOTU4MDgzNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg3MTY4OTEtNTEwOTQyYzMtN2RiMy00YTQ1LTliOTAtN2RmM2IwY2MzZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMGI3ZDExMjY2ODNiNDZiZWU2NDY2ZGQ3MDlmYzBiZTNjNzY3YzZmNWJkNzYyNWU4YjlkMTBmNzY3MjJhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BVkyU94p7yM6GuJf5utAlLER7JjM31JhGCLWK9OA4sA) 这是关了其他脚本有按钮的情况 ![image](https://private-user-images.githubusercontent.com/14146754/378717650-51e13d87-c2dd-48c8-908e-dfdfb7e24d59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODExMzYsIm5iZiI6MTcyOTU4MDgzNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg3MTc2NTAtNTFlMTNkODctYzJkZC00OGM4LTkwOGUtZGZkZmI3ZTI0ZDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZTRjZDVmNGZkNDE0N2JmZTg1MzY2MzA5MmFlM2E3MjcyOTEzMDEyNmQyN2I0MjM0YjBhZmQzZmYzNTRlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E9zefctR4LXxg7HOIVUuUaPlCVMGoXw1iM4r-Q3Hvck) 这是开了别的脚本但是还有按钮的情况 ![image](https://private-user-images.githubusercontent.com/14146754/378718320-eda7e985-beb9-4d54-9eda-1757d0fbaf30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODExMzYsIm5iZiI6MTcyOTU4MDgzNiwicGF0aCI6Ii8xNDE0Njc1NC8zNzg3MTgzMjAtZWRhN2U5ODUtYmViOS00ZDU0LTllZGEtMTc1N2QwZmJhZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNTdlNmM4MzhiZTkwZDQzYTNiYWJmZjAxNzI3MzY4MGJjYThjMTRmNmM2ZjliM2QyYmE1NTY2NjFiYWM1NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c6fY7DwTBRInipihBXkhJIFdCnyi7xzn4_tivPFMlxY) 这是开了别的脚本但是没有显示按钮的情况
> 
> 第三圖，這是明顯是跟其他脚本衝突了 有沒有沒開其他脚本但是沒有顯示按鈕的截圖？

![image](https://github.com/user-attachments/assets/1b2cc1e1-3311-4760-8cff-2833c02ca23a)

**Comment by eric2788** [comment]
@u2shana humm e2e 测试没看到有问题: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11495591034/job/31995607368#step:9:108

**Comment by u2shana** [comment]
> @u2shana humm e2e 测试没看到有问题: https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11495591034/job/31995607368#step:9:108
> 
> 你确定不是由别的脚本冲突引起的？

可能是吧，解决不了的话也没办法，但也能用

**Comment by eric2788** [comment]
> > @u2shana humm e2e 测试没看到有问题: [eric2788/bilibili-vup-stream-enhancer/actions/runs/11495591034/job/31995607368#step:9:108](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11495591034/job/31995607368#step:9:108)
> > 你确定不是由别的脚本冲突引起的？
> 
> 可能是吧，解决不了的话也没办法，但也能用

我在大海报房间测出来了

**Comment by eric2788** [comment]
@u2shana 试试这个 https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196
我优化了元素抓取

**Comment by u2shana** [comment]
> @u2shana 试试这个 https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196 我优化了元素抓取

这版正常了。但是旧版的配置好像不能直接导入

**Comment by eric2788** [comment]
> > @u2shana 试试这个 [eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196) 我优化了元素抓取
> 
> 这版正常了。但是旧版的配置好像不能直接导入

怎么说？

**Comment by u2shana** [comment]
> > > @u2shana 试试这个 [eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196) 我优化了元素抓取
> > 
> > 
> > 这版正常了。但是旧版的配置好像不能直接导入
> 
> 怎么说？
按钮能正常显示，但是旧版配置导入会报错

**Comment by eric2788** [comment]
> > > > @u2shana 试试这个 [eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196) 我优化了元素抓取
> > > 
> > > 
> > > 这版正常了。但是旧版的配置好像不能直接导入
> > 
> > 
> > 怎么说？
> > 按钮能正常显示，但是旧版配置导入会报错

https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11502793466
试试这个版本看看还有没有导入问题

**Comment by eric2788** [comment]
> > > > @u2shana 试试这个 [eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196](https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11501093196) 我优化了元素抓取
> > > 
> > > 
> > > 这版正常了。但是旧版的配置好像不能直接导入
> > 
> > 
> > 怎么说？
> > 按钮能正常显示，但是旧版配置导入会报错

试试这个版本看看还有没有导入问题:
https://github.com/eric2788/bilibili-vup-stream-enhancer/actions/runs/11502861167

**Comment by eric2788** [comment]
@u2shana 測都測了，能順手幫我測試同傳字幕AI總結？在功能設定 -> 同傳字幕 -> AI 設定那邊
