### ISSUE TITLE
[Bug]: 找不到屏幕适配相关设置

### ISSUE THREAD

**Issue by jkfujr** [eric2788/bilibili-vup-stream-enhancer#94]
### 感谢您抽出时间填写此问题回报！

- [X] 我已经搜索了现有的问题，并且确认我的问题是独特的

### 问题描述

![截图_2024-12-08_19-49-59](https://github.com/user-attachments/assets/cb49bf93-83a1-4e17-803c-6dbbd1bd8390)

屏幕: `2560*1440`

插件: `默认设置`

我在设置中找不到屏幕适配相关设置，能否增加个搜索框方便查找功能

### 期望结果

关闭提示/功能开关

### 复现步骤

1. 插件默认设置，进入直播间提示

### 浏览器

Chromium 118.0.5993.159

### 其他浏览器上的复现

Chrome

### 扩展版本

v2.0.3.1028

**Comment by eric2788** [comment]
目前有影響插件正常運作嗎

**Comment by eric2788** [comment]
適配功能在右邊導航欄 實驗室 那邊

**Comment by eric2788** [comment]
![image](https://github.com/user-attachments/assets/7358d389-8850-45b7-a4f5-3537db08f335)

**Comment by jkfujr** [comment]
> 目前有影響插件正常運作嗎

这倒是不影响，不过每次打开直播间都会提示就挺烦的）
